version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    restart: always
